language: java
script:
- "./mvnw clean compile"
- "./mvnw package -P jar"
- "./mvnw package -P war"
before_deploy:
- git config --local user.name "Kenneth Wussmann"
- git config --local user.email "kenneth@wussmann.net"
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
- git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  file_glob: true
  file:
    - "target/*.jar"
    - "target/*.war"
  on:
    branch: master
    repo: KennethWussmann/discord-temperature
