language: java
script:
- "./mvnw clean compile"
- "./mvnw package -P jar"
- "./mvnw package -P war"
before_deploy:
- git config --local user.name "Kenneth Wussmann"
- git config --local user.email "kenneth@wussmann.net"
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
- git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key:
    secure: fxjNA5xdcGhL4sBujaH+tdGsFNqyoTTSYZzK26lStkRoLds4kJhb4sfBPQaTcKbIRmE2o6l43V95pCj0pxa05jYuRiTcgX1KXtkX6jGhfBjQO1klJZY0AjpEE/BsyA/A8e/meuT8CyThbFSHzOyVK6227d0RyjsRhQkRYhlM8diKLq5d3dH6RKfbFe+MZTnquhhociwM/KvtnYN72H6njooEO2G+nCcj0o5W2/nn6VKy1B3UoDdQuwyI88wf0oD4xIgXJVU8/Hf7XjwiK1w61v/3u7tRlM1qil13bfNrrRJKj8Iv4u/9YYhJXWSbDgrA5aKgMMBhMOH3Cnsf5a6GG8HPPZTzC0SSW1W5Tmbl5lJFw69lZ0V958hvuXXv+w2p0YVCf6tdNZEebgRA/PoANut9phsOlCmF2+tZD61U3wyjtIpj6m6NA7yEzb0tqZ26t2qFW7GoX/p979mxQLjOlb1Bn3Ld1RekuJvY9qxIc2t4/jgrJiexqJCz4yCzr9L9YGQE0AO01cXgCrUSaQHn4AXNVSYD2n3LuOttOaZS/NY19/1z5GpomEH3kkI2LbDSVjbnA23z9WI/9StzNcPO0OuuAaGupWJfY5vY3rxAOzXKpldTMtw7DJ3FmCZ41xjBzQSKAxBGN3q3SLg0W2Pta3l03bOFxdf0r05JUDMxj2Y=
  file:
    - "target/*.jar"
    - "target/*.war"
  on:
    branch: master
    repo: KennethWussmann/discord-temperature
